app_settings:
  bot_name: DV
  print_enable: false
gpt_chat_settings:
  frequency_penalty: 0
  max_messages_count: 17
  max_tokens: 1024
  max_words_count: 2700
  model: gpt-3.5-turbo
  presence_penalty: 0
  temperature: 0.5
  top_p: 1
