app_settings:
  bot_name: DV
  print_enable: true
gpt_chat_settings:
  frequency_penalty: 0
  max_messages_count: 21
  max_tokens: 1024
  max_words_count: 1000
  model: gpt-4-turbo
  presence_penalty: 0
  temperature: 0.5
  top_p: 1
gpt_image_settings:
  model: dall-e-3
  size: "1024x1024"
